# Generated by Django 2.1.5 on 2021-05-31 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaleproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='wholesaleproductorders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='size',
        ),
        migrations.DeleteModel(
            name='WholeSaleProduct',
        ),
        migrations.DeleteModel(
            name='WholeSaleProductOrders',
        ),
    ]
